FROM node:20-bullseye-slim

ARG APP_USER=node
ARG APP_HOME=/opt/lpmc
ARG APP_EXECUTABLE=server.js
ENV ENV_APP_EXECUTABLE=$APP_EXECUTABLE

RUN mkdir -p $APP_HOME
ADD .next/standalone $APP_HOME
ADD .next/static $APP_HOME/.next/static
ADD public $APP_HOME/public

WORKDIR $APP_HOME
RUN chown -R $APP_USER:$APP_USER $APP_HOME

USER $APP_USER

EXPOSE 3100

ENTRYPOINT NODE_OPTIONS=${NODE_OPTIONS} NODE_ENV=${NODE_ENV} node ./$ENV_APP_EXECUTABLE
